dist: trusty
# trusty requires virtualization, which is set by 'sudo: required'
sudo: required
os:
    - linux
cache:
    timeout: 1000
    directories:
        - cs/packages
        - $HOME/.ccache
        - $HOME/.stack
        - $HOME/docker-images
services:
    - docker
env:
    global:
        - BUILD_SCRIPT=tools/ci-scripts/linux/build_travis.sh
jobs:
    include:
        - stage: Cache warm-up
          script: $BUILD_SCRIPT cache

        - stage: Build
          script: $BUILD_SCRIPT cs
        - script: $BUILD_SCRIPT cpp-core 1.65.1 gcc
        - script: $BUILD_SCRIPT cpp-core 1.64.0 clang
        - script: $BUILD_SCRIPT cpp-core 1.63.0 clang
        - script: $BUILD_SCRIPT cpp-core 1.62.0 clang
        - script: $BUILD_SCRIPT cpp-core 1.61.0 clang
        - script: $BUILD_SCRIPT cpp-core 1.60.0 clang
        - script: $BUILD_SCRIPT cpp-core 1.59.0 clang
        - script: $BUILD_SCRIPT cpp-core 1.58.0 clang
        - script: $BUILD_SCRIPT cpp-comm 1.63.0 clang
        - script: $BUILD_SCRIPT cpp-grpc 1.65.1 gcc
        - script: $BUILD_SCRIPT cpp-grpc 1.64.0 clang
        - script: $BUILD_SCRIPT cpp-grpc 1.63.0 clang
        - script: $BUILD_SCRIPT hs
        - script: $BUILD_SCRIPT java
