<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>bond</string>
    </array>
    <key>name</key>
    <string>Bond</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#commonStuff</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.namespace.bond</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.deprecated</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.namespace.bond</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(namespace)\s+(?:(cpp|csharp)\s+)?(.+)</string>
        <key>name</key>
        <string>meta.namespace.bond</string>
      </dict>
      <dict>
        <key>match</key>
        <string>^import\s+</string>
        <key>name</key>
        <string>keyword.other.import.bond</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(enum)\s+(.+)$</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.enum.bond</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.enum.bond</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>name</key>
        <string>meta.enum.bond</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#commonStuff</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.bond</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^\s*([^\s]*)\s</string>
            <key>name</key>
            <string>entity.name.type.enum.value.bond</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(struct)\s+(.+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.struct.bond</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.struct.bond</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>name</key>
        <string>meta.struct.bond</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^\s*(\d+)</string>
            <key>name</key>
            <string>constant.numeric.bond</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#commonStuff</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>commonStuff</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>u?int(8|16|32|64)|blob|bonded|bool|double|float|list|map|nullable|set|string|vector|void|wstring</string>
            <key>name</key>
            <string>constant.language</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
            <key>name</key>
            <string>constant.numeric.bond</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(true|false|nothing)\b</string>
            <key>name</key>
            <string>constant.language</string>
          </dict>
          <dict>
            <key>match</key>
            <string>//.+</string>
            <key>name</key>
            <string>comment.line.double-slash.bond</string>
          </dict>
          <dict>
            <key>match</key>
            <string>"[^"]+"</string>
            <key>name</key>
            <string>string.quoted.double.cs</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.bond</string>
    <key>uuid</key>
    <string>d902f5e0-8df4-4bd1-b0e8-e5915501d0cc</string>
  </dict>
</plist>
