-- Copyright (c) Microsoft. All rights reserved.
-- Licensed under the MIT license. See LICENSE file in the project root for full license information.

{-# LANGUAGE QuasiQuotes, OverloadedStrings #-}

module Bond.Template.Util
    ( toText
    , commonHeader
    , mconcatMap
    , mconcatFor
    , sepBy
    , sepEndBy
    , sepBeginBy
    , sep
    , commaSep
    , newlineSep
    , commaLineSep
    , newlineSepEnd
    , newlineBeginSep
    , doubleLineSep
    , doubleLineSepEnd
    ) where

import System.FilePath
import Data.Monoid
import Data.Word
import Data.String
import Data.Text.Lazy (justifyRight)
import Data.Text.Lazy.Builder
import Text.Shakespeare.Text
import Bond.Version
import Bond.Util
import Bond.Schema

instance ToText Word16 where
    toText = toText . show

instance ToText Double where
    toText = toText . show

instance ToText Integer where
    toText = toText . show

mconcatMap f = foldr (mappend . f) mempty

mconcatFor m f = mconcatMap f m

sep s = sepBy s toText

commaSep :: ToText t => [t] -> Builder
commaSep = sepBy ", " toText

indent n = justifyRight (4 * n) ' ' ""

commaLine n = [lt|,
#{indent n}|]

newLine n = [lt|
#{indent n}|]

doubleLine n = [lt|

#{indent n}|]

newlineSep = sepBy . newLine
commaLineSep = sepBy . commaLine
newlineSepEnd = sepEndBy . newLine
newlineBeginSep = sepBeginBy . newLine
doubleLineSep = sepBy . doubleLine
doubleLineSepEnd = sepEndBy . doubleLine

commonHeader file = [lt|
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler #{majorVersion}.#{minorVersion}
//   File : #{file}
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------
|]

