---
name: Linux CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "${{ matrix.env.FLAVOR }} ${{ matrix.env.BOOST }} ${{ matrix.env.COMPILER }}"
    runs-on: "ubuntu-latest"

    container:
      image: bondciimages.azurecr.io/ubuntu-1604:build-32869346

    strategy:
      fail-fast: false
      matrix:
        env:
          - { FLAVOR: cs }
          - { FLAVOR: cpp-core, BOOST: 1.66.0, COMPILER: clang }
          - { FLAVOR: cpp-grpc, BOOST: 1.66.0, COMPILER: clang }
          - { FLAVOR: hs }
          - { FLAVOR: java }

    env: ${{ matrix.env }}

    steps:
      - name: "Update git - ver has to be at least Git 2.18"
        run: |
          add-apt-repository ppa:git-core/ppa -y
          apt-get update
          apt-get install --no-install-recommends git -y

      - name: "Git checkout"
        uses: "actions/checkout@v2"
        with:
          submodules: recursive

      - name: Cache stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: stack-${{ matrix.env.FLAVOR }}-${{ matrix.env.BOOST }}-${{ matrix.env.COMPILER }}--${{ hashFiles('**/compiler/stack.yaml','**/compiler/package.yaml','**/compiler/stack.yaml.lock') }}
          restore-keys: |
            stack-${{ matrix.env.FLAVOR }}-${{ matrix.env.BOOST }}-${{ matrix.env.COMPILER }}-

      - name: "Build and test for ${{ matrix.env.FLAVOR }} ${{ matrix.env.BOOST }} ${{ matrix.env.COMPILER }}"
        run: |
          set -xe
          mkdir -p /github/home/.stack
          sed -i 's@/root/bond@'"$(pwd)"'@g' tools/ci-scripts/linux/build.zsh
          sed -i 's@/root/bond@'"$(pwd)"'@g' tools/ci-scripts/linux/build_cpp-common.zsh
          zsh tools/ci-scripts/linux/build.zsh $(pwd) ${{ env.FLAVOR }} ${{ env.BOOST }} ${{ env.COMPILER}}
